development:
  PUSHER_APP_ID: '726459'
  PUSHER_KEY: '360554eef31f7e3cad83'
  PUSHER_SECRET: '228fba288250ac893f60'
  PUSHER_CLUSTER: 'us3'
staging:
  PUSHER_APP_ID: '726460'
  PUSHER_KEY: '6e0d332588ad22f32870'
  PUSHER_SECRET: '1dc6cb2d54f53560acbb'
  PUSHER_CLUSTER: 'us3'
production:
  PUSHER_APP_ID: '726461'
  PUSHER_KEY: 'f749e06841dc3e887a75'
  PUSHER_SECRET: '2d80b349026516b76f7b'
  PUSHER_CLUSTER: 'us3'
